var guiData = {
	"version": 2,
	"magic": "cantk",
	"meta": {
		"general": {
			"appid": "4acd8a576a264abba7abc0c626d299f2",
			"appversion": "1.0.0",
			"appname": "Chat",
			"appdesc": "Chat",
			"gapversion": "1.0",
			"screenscale": "fix-width",
			"orientation": "portrait",
			"developer": "Unkown <unkown@tangide.com>",
			"appIcon": "/drawapp8/images/appicons/96.png",
			"screenShot1": "",
			"screenShot2": "",
			"screenShot3": ""
		},
		"extlibs": [],
		"docChangedTime": 1456445835124,
		"docSavedTime": 1456445838428,
		"extfonts": []
	},
	"deviceConfig": {
		"name": "general",
		"platform": "android",
		"lcdDensity": "hdpi"
	},
	"docid": "cn_release239660f0-dae2-11e5-b813-91b567b2df1d",
	"fileList": [],
	"wm": {
		"type": "ui-window-manager",
		"name": "window-manager",
		"uid": 16616,
		"z": 0,
		"w": 480,
		"h": 800,
		"pivotX": 0.5,
		"pivotY": 0.5,
		"rotation": 0,
		"opacity": 1,
		"hMargin": 0,
		"vMargin": 0,
		"scaleX": 1,
		"scaleY": 1,
		"runtimeVisible": true,
		"enable": true,
		"visible": true,
		"text": "",
		"x": 0,
		"y": 0,
		"style": {
			"lineWidth": 2,
			"lineColor": "Green",
			"fillColor": "Black",
			"textColor": "Black",
			"fontSize": 24,
			"fontFamily": "serif"
		},
		"soundEffectsEnalbe": true,
		"soundMusicAutoPlay": true,
		"current": 0,
		"sceneIdIndex": 4,
		"xAttr": 0,
		"yAttr": 0,
		"widthAttr": 2,
		"heightAttr": 0,
		"xParam": 1,
		"yParam": 1,
		"widthParam": 1,
		"heightParam": 1,
		"images": {
			"display": 2,
			"force-landscape-tips": "cantk-game/assets/images/force_landscape.png",
			"force-portrait-tips": "cantk-game/assets/images/force_portrait.png"
		},
		"events": {
			"onClick": null,
			"onChanged": null
		},
		"settings": {},
		"children": [
			{
				"type": "ui-scene",
				"name": "win-main",
				"uid": 16617,
				"z": 0,
				"w": 480,
				"h": 800,
				"pivotX": 0.5,
				"pivotY": 0.5,
				"rotation": 0,
				"opacity": 1,
				"hMargin": 0,
				"vMargin": 0,
				"scaleX": 1,
				"scaleY": 1,
				"runtimeVisible": true,
				"enable": true,
				"visible": true,
				"text": "",
				"x": 0,
				"y": 0,
				"style": {
					"lineWidth": 2,
					"lineColor": "#C8C8C8",
					"fillColor": "#2F3234",
					"textColor": "Blue",
					"fontSize": 15,
					"fontFamily": "sans"
				},
				"enablePhysics": false,
				"showFPS": true,
				"maxFPSMode": true,
				"gravityY": 10,
				"pixelsPerMeter": 100,
				"virtualWidth": 0,
				"virtualHeight": 0,
				"xOffset": 0,
				"yOffset": 0,
				"animHint": "none",
				"refLinesV": [],
				"refLinesH": [],
				"sceneId": "game_scene_1",
				"xAttr": 0,
				"yAttr": 0,
				"widthAttr": 2,
				"heightAttr": 2,
				"xParam": 1,
				"yParam": 1,
				"widthParam": 1,
				"heightParam": 1,
				"images": {
					"display": 3
				},
				"events": {
					"onClick": null,
					"onSystemInit": "window.Chat = {};\r\nwindow.Chat.IP = \"211.149.169.202\";\r\nwindow.Chat.PORT = 7290;",
					"onLoad": null,
					"onOpen": "",
					"onBeforeOpen": "var me = this;\r\nvar win = this.getWindow();\r\nvar btn_top = win.find(\"btn_top\");\r\nvar group_message = win.find(\"group_message\");\r\nvar list_message = win.find(\"list_message\");\r\nvar group_down = win.find(\"group_down\");\r\nwindow.player_name = localStorage.getItem(\"player_name\");\r\nlist_message.height = win.height - btn_top.height - group_down.height;\r\n\r\nwindow.show_prompt = function()\r\n{\r\n    var ask = function()\r\n    {\r\n        var name = window.prompt(\"Your name?\", \"\");\r\n        \r\n        if(!name)\r\n        {\r\n            ask();\r\n        }\r\n        else\r\n        {\r\n            window.player_name = name;\r\n            localStorage.setItem(\"player_name\", name);\r\n        }\r\n    };\r\n    \r\n    if(!window.player_name)\r\n    {\r\n       ask(); \r\n    }\r\n};\r\n\r\nwindow.onopen = function()\r\n{\r\n    window.show_prompt();\r\n\r\n    var data = \r\n    {\r\n        \"type\":       \"login\",\r\n        \"client_name\": window.player_name,\r\n        \"room_id\":     1\r\n    };\r\n\r\n   window.send(data);\r\n};\r\n\r\nwindow.onmessage = function(e)\r\n{\r\n    var data = eval(\"(\"+e.data+\")\");\r\n    console.dir(\"[receive]: \" + e.data);\r\n\r\n    switch(data['type'])\r\n    {\r\n        case \"ping\":\r\n\r\n            window.ws.send({\"type\": \"pong\"});\r\n            break;\r\n\r\n        case \"login\":\r\n\r\n            if(data['client_list'])\r\n            {\r\n                window.client_list = data['client_list'];\r\n            }\r\n            else\r\n            {\r\n                window.client_list[data['client_id']] = data['client_name']; \r\n            }\r\n\r\n            window.add_message(\r\n                data[\"client_id\"],\r\n                data[\"client_name\"], \r\n                data[\"client_name\"] + \" joins the chat room.\", \r\n                data[\"time\"]\r\n            );\r\n\r\n            console.log(data['client_name']+\" logins successfully!\");\r\n            break;\r\n\r\n        case \"say\":\r\n\r\n            window.add_message(\r\n                data['from_client_id'],\r\n                data['from_client_name'], \r\n                data['content'], \r\n                data['time']\r\n            );\r\n            break;\r\n\r\n        case \"logout\":\r\n\r\n            window.add_message(\r\n                data['from_client_id'],\r\n                data['from_client_name'], \r\n                data['from_client_name'] + ' left.', \r\n                data['time']\r\n            );\r\n\r\n            delete window.client_list[data['from_client_id']];\r\n            break;\r\n            \r\n        default:\r\n            break;\r\n    }\r\n};\r\n\r\nwindow.send = function(data)\r\n{\r\n    var msg = JSON.stringify(data);\r\n    window.ws.send(msg);\r\n};\r\n\r\nwindow.send_message = function(value)\r\n{\r\n    var data = \r\n    {\r\n        \"type\":           \"say\",\r\n        \"to_client_id\":   \"all\",\r\n        \"to_client_name\": \"all\",\r\n        \"content\":        value\r\n    };\r\n\r\n    window.send(data);\r\n};\r\n\r\nwindow.add_message = function(from_client_id, from_client_name, content, time)\r\n{\r\n    var child = null;\r\n\r\n    if(!window.first_flag)\r\n    {\r\n        window.first_flag = true;\r\n        child = list_message.children[0];\r\n    }\r\n    else\r\n    {\r\n        child = list_message.dupChild(list_message.children[0].name, list_message.children.length - 1);\r\n    }\r\n\r\n    var group_role = child.find(\"group_role\");\r\n    var image_head = group_role.find(\"image_head\");\r\n    var group_content = group_role.find(\"group_content\");\r\n    var label_content = group_content.find(\"label_content\");\r\n    var label_name = group_role.find(\"label_name\");\r\n    var direction = \"\";\r\n    var value = \"\";\r\n    var head_x = 5;   \r\n\r\n    //TODO: from_client_id\r\n    if(from_client_name == window.player_name)\r\n    {\r\n        direction = \"right\";\r\n        value = time + \"  \" + from_client_name;\r\n        head_x = win.width - image_head.width - 5;\r\n    }\r\n    else\r\n    {\r\n        direction = \"left\";\r\n        value = from_client_name + \"  \" + time;\r\n    }\r\n\r\n    image_head.x = head_x; \r\n    image_head.setValue(from_client_name.charCodeAt() % 14);\r\n    label_content.setValue(content);\r\n    label_name.setTextAlign(direction);\r\n    label_name.setValue(value);\r\n    group_role.setVisible(true);\r\n    list_message.relayoutChildren();\r\n    list_message.scrollToEnd();\r\n};\r\n\r\nwindow.connect = function()\r\n{\r\n    if(!window.ws)\r\n    {\r\n        console.dir(Chat);\r\n        window.ws = new WebSocket(\"ws://\" + window.Chat.IP + \":\" + window.Chat.PORT);\r\n        window.ws.onopen = window.onopen;\r\n        window.ws.onmessage = window.onmessage; \r\n\r\n        window.ws.onclose = function() \r\n        {\r\n            console.warn(\"Disconnected from the server!\");\r\n        };\r\n\r\n        window.ws.onerror = function(e) \r\n        {\r\n            console.log(\"[error]: \" + e.data);\r\n        };\r\n    }\r\n};\r\n\r\nwindow.connect();",
					"onClose": null,
					"onSwitchToBack": null,
					"onSwitchToFront": null,
					"onGesture": null,
					"onKeyDown": null,
					"onKeyUp": null,
					"onPointerDown": null,
					"onPointerMove": null,
					"onPointerUp": null,
					"onDoubleClick": null,
					"onMultiTouch": null,
					"onSwipeLeft": null,
					"onSwipeRight": null,
					"onSwipeUp": null,
					"onSwipeDown": null,
					"onUnload": null
				},
				"settings": {},
				"propertySheetDesc": {},
				"children": [
					{
						"type": "ui-list-view",
						"name": "list_message",
						"uid": 17368,
						"z": 2,
						"w": 480,
						"h": 712,
						"pivotX": 0.5,
						"pivotY": 0.5,
						"rotation": 0,
						"opacity": 1,
						"hMargin": 0,
						"vMargin": 0,
						"scaleX": 1,
						"scaleY": 1,
						"spacer": 0,
						"runtimeVisible": true,
						"enable": true,
						"visible": true,
						"text": "",
						"locked": false,
						"x": 0,
						"y": 43,
						"style": {
							"lineWidth": 2,
							"lineColor": "Orange",
							"fillColor": "#f0f0f0",
							"textColor": "Blue",
							"fontSize": 16,
							"fontFamily": "serif"
						},
						"itemHeightVariable": true,
						"itemHeight": 84,
						"xAttr": 3,
						"yAttr": 0,
						"widthAttr": 2,
						"heightAttr": 0,
						"xParam": 1,
						"yParam": 1,
						"widthParam": 1,
						"heightParam": 1,
						"images": {
							"display": 2,
							"scrollBarImg": "assets/controls/scrollbar.png"
						},
						"events": {
							"onClick": "var me = this;\nvar win = this.getWindow();\n//显示对象\nwin.find(\"group_plus\").setVisible(false);",
							"onUpdateData": null,
							"onScrollOutOfRange": null
						},
						"children": [
							{
								"type": "ui-list-item",
								"name": "item_0",
								"uid": 19213,
								"z": 0,
								"w": 480,
								"h": 100,
								"pivotX": 0.5,
								"pivotY": 0.5,
								"rotation": 0,
								"opacity": 1,
								"hMargin": 0,
								"vMargin": 0,
								"scaleX": 1,
								"scaleY": 1,
								"roundRadius": 5,
								"runtimeVisible": true,
								"enable": true,
								"visible": true,
								"text": "",
								"x": 0,
								"y": 0,
								"style": {
									"lineWidth": 0,
									"lineColor": "rgba(0,0,0,0)",
									"fillColor": "rgba(0,0,0,0)",
									"textColor": "rgba(0,0,0,0)",
									"fontSize": 16,
									"fontFamily": "serif",
									"focusedFillColor": "rgba(0,0,0,0)",
									"overFillColor": "rgba(0,0,0,0)"
								},
								"xAttr": 0,
								"yAttr": 0,
								"widthAttr": 2,
								"heightAttr": 0,
								"xParam": 1,
								"yParam": 1,
								"widthParam": 1,
								"heightParam": 1,
								"images": {
									"display": 2
								},
								"events": {
									"onClick": null,
									"onLongPress": null,
									"onRemoved": null
								},
								"children": [
									{
										"type": "ui-group",
										"name": "group_role",
										"uid": 18621,
										"z": 0,
										"w": 480,
										"h": 100,
										"pivotX": 0.5,
										"pivotY": 0.5,
										"rotation": 0,
										"opacity": 1,
										"hMargin": 0,
										"vMargin": 0,
										"scaleX": 1,
										"scaleY": 1,
										"roundRadius": 5,
										"runtimeVisible": false,
										"enable": true,
										"visible": true,
										"text": "",
										"locked": false,
										"x": 0,
										"y": 0,
										"style": {
											"lineWidth": 2,
											"lineColor": "rgba(0,0,0,0)",
											"fillColor": "rgba(0,0,0,0)",
											"textColor": "Blue",
											"fontSize": 24
										},
										"xAttr": 3,
										"yAttr": 4,
										"widthAttr": 2,
										"heightAttr": 0,
										"xParam": 1,
										"yParam": 1,
										"widthParam": 1,
										"heightParam": 1,
										"images": {
											"display": 2
										},
										"events": {
											"onClick": null,
											"onInit": null
										},
										"children": [
											{
												"type": "ui-image",
												"name": "image_head",
												"uid": 14168,
												"z": 0,
												"w": 50,
												"h": 50,
												"pivotX": 0.5,
												"pivotY": 0.5,
												"rotation": 0,
												"opacity": 1,
												"hMargin": 0,
												"vMargin": 0,
												"scaleX": 1,
												"scaleY": 1,
												"runtimeVisible": true,
												"enable": true,
												"visible": true,
												"text": "",
												"x": 5,
												"y": 0,
												"style": {
													"lineWidth": 2,
													"lineColor": "#7d471b",
													"fillColor": "White",
													"textColor": "Blue",
													"fontSize": 16,
													"fontFamily": "sans"
												},
												"keepSizeWithImage": false,
												"xAttr": 0,
												"yAttr": 4,
												"widthAttr": 0,
												"heightAttr": 0,
												"xParam": 1,
												"yParam": 1,
												"widthParam": 1,
												"heightParam": 1,
												"imageScaleX": "1.000",
												"imageScaleY": "1.000",
												"images": {
													"display": 3,
													"default_bg": "assets/Chat/res/headicon/14.png",
													"option_image_0": "assets/Chat/res/headicon/1.png",
													"option_image_1": "assets/Chat/res/headicon/2.png",
													"option_image_2": "assets/Chat/res/headicon/3.png",
													"option_image_3": "assets/Chat/res/headicon/4.png",
													"option_image_4": "assets/Chat/res/headicon/5.png",
													"option_image_5": "assets/Chat/res/headicon/6.png",
													"option_image_6": "assets/Chat/res/headicon/7.png",
													"option_image_7": "assets/Chat/res/headicon/8.png",
													"option_image_8": "assets/Chat/res/headicon/9.png",
													"option_image_9": "assets/Chat/res/headicon/10.png",
													"option_image_10": "assets/Chat/res/headicon/11.png",
													"option_image_11": "assets/Chat/res/headicon/12.png",
													"option_image_12": "assets/Chat/res/headicon/13.png",
													"option_image_13": "assets/Chat/res/headicon/14.png"
												},
												"events": {
													"onClick": null,
													"onDoubleClick": null,
													"onUpdateTransform": null
												},
												"children": []
											},
											{
												"type": "ui-group",
												"name": "group_content",
												"uid": 17605,
												"z": 1,
												"w": 356,
												"h": 56,
												"pivotX": 0.5,
												"pivotY": 0.5,
												"rotation": 0,
												"opacity": 1,
												"hMargin": 0,
												"vMargin": 0,
												"scaleX": 1,
												"scaleY": 1,
												"roundRadius": 5,
												"runtimeVisible": true,
												"enable": true,
												"visible": true,
												"text": "",
												"x": 62,
												"y": 23,
												"style": {
													"lineWidth": 1,
													"lineColor": "#4A4949",
													"fillColor": "rgba(0,0,0,0)",
													"textColor": "Blue",
													"fontSize": 24
												},
												"xAttr": 3,
												"yAttr": 0,
												"widthAttr": 0,
												"heightAttr": 0,
												"xParam": 1,
												"yParam": 1,
												"widthParam": 1,
												"heightParam": 1,
												"images": {
													"display": 2
												},
												"events": {
													"onClick": null,
													"onInit": null
												},
												"children": [
													{
														"type": "ui-label",
														"name": "label_content",
														"uid": 18607,
														"z": 0,
														"w": 356,
														"h": 56,
														"pivotX": 0.5,
														"pivotY": 0.5,
														"rotation": 0,
														"opacity": 1,
														"hMargin": 5,
														"vMargin": 5,
														"scaleX": 1,
														"scaleY": 1,
														"runtimeVisible": true,
														"enable": true,
														"visible": true,
														"text": "对应的属性页。新版本Hola 系统设置。对应的属性页。新版本Hola 系统设置。对应的属性页。新版本Hola 系统设置。对应的属性页。新版本Hola 系统设置。对应的属性页。新版本Hola 系统设置。对应的属性页。新版本Hola 系统设置。对应的属性页。新版本Hola 系统设置。对应的属性页。新版本Hola 系统设置。",
														"locked": false,
														"x": 0,
														"y": 0,
														"style": {
															"lineWidth": 2,
															"lineColor": "Red",
															"fillColor": "rgba(0,0,0,0)",
															"textColor": "#ffffff",
															"fontSize": 15,
															"fontFamily": "serif"
														},
														"hTextAlign": "left",
														"vTextAlign": "top",
														"xAttr": 2,
														"yAttr": 2,
														"widthAttr": 2,
														"heightAttr": 2,
														"xParam": 0,
														"yParam": 0,
														"widthParam": 1,
														"heightParam": 1,
														"images": {
															"display": 2
														},
														"events": {
															"onClick": null,
															"onChanged": null,
															"onUpdateTransform": null
														},
														"children": []
													}
												]
											},
											{
												"type": "ui-label",
												"name": "label_name",
												"uid": 18607,
												"z": 2,
												"w": 360,
												"h": 19,
												"pivotX": 0.5,
												"pivotY": 0.5,
												"rotation": 0,
												"opacity": 1,
												"hMargin": 5,
												"vMargin": 5,
												"scaleX": 1,
												"scaleY": 1,
												"runtimeVisible": true,
												"enable": true,
												"visible": true,
												"text": "Mary",
												"x": 60,
												"y": 0,
												"style": {
													"lineWidth": 2,
													"lineColor": "Red",
													"fillColor": "rgba(0,0,0,0)",
													"textColor": "#F0E6E6",
													"fontSize": 12,
													"fontFamily": "serif"
												},
												"hTextAlign": "left",
												"vTextAlign": "middle",
												"xAttr": 3,
												"yAttr": 4,
												"widthAttr": 0,
												"heightAttr": 0,
												"xParam": 1,
												"yParam": 1,
												"widthParam": 1,
												"heightParam": 1,
												"images": {
													"display": 2
												},
												"events": {
													"onClick": null,
													"onChanged": null,
													"onUpdateTransform": null
												},
												"children": []
											}
										]
									}
								]
							}
						]
					},
					{
						"type": "ui-color-button",
						"name": "btn_top",
						"uid": 11813,
						"z": 13,
						"w": 480,
						"h": 41,
						"pivotX": 0.5,
						"pivotY": 0.5,
						"rotation": 0,
						"opacity": 1,
						"hMargin": 0,
						"vMargin": 0,
						"scaleX": 1,
						"scaleY": 1,
						"roundRadius": 0,
						"runtimeVisible": true,
						"enable": true,
						"visible": true,
						"text": "One Piece",
						"x": 0,
						"y": 0,
						"style": {
							"lineWidth": 0,
							"lineColor": "#666666",
							"fillColor": "#666666",
							"textColor": "#FFFFFF",
							"fontSize": 16,
							"fontFamily": "serif",
							"activeFillColor": "#666666"
						},
						"xAttr": 3,
						"yAttr": 4,
						"widthAttr": 2,
						"heightAttr": 0,
						"xParam": 1,
						"yParam": 1,
						"widthParam": 1,
						"heightParam": 1,
						"images": {
							"display": 2
						},
						"events": {
							"onClick": "",
							"onUpdateTransform": null
						},
						"children": [
							{
								"type": "ui-label",
								"name": "label_plus",
								"uid": 18607,
								"z": 0,
								"w": 64,
								"h": 36,
								"pivotX": 0.5,
								"pivotY": 0.5,
								"rotation": 0,
								"opacity": 0.7,
								"hMargin": 5,
								"vMargin": 5,
								"scaleX": 1,
								"scaleY": 1,
								"runtimeVisible": true,
								"enable": true,
								"visible": true,
								"text": "+",
								"x": 416,
								"y": 2,
								"style": {
									"lineWidth": 2,
									"lineColor": "Red",
									"fillColor": "rgba(0,0,0,0)",
									"textColor": "#ffffff",
									"fontSize": 26,
									"fontFamily": "serif"
								},
								"hTextAlign": "center",
								"vTextAlign": "middle",
								"xAttr": 1,
								"yAttr": 3,
								"widthAttr": 0,
								"heightAttr": 0,
								"xParam": 0,
								"yParam": 1,
								"widthParam": 1,
								"heightParam": 1,
								"images": {
									"display": 2
								},
								"events": {
									"onClick": "var me = this;\nvar win = this.getWindow();\nvar group_plus = win.find(\"group_plus\");\n//显示对象\ngroup_plus.setVisible(!group_plus.visible);",
									"onChanged": null,
									"onUpdateTransform": null
								},
								"children": []
							}
						]
					},
					{
						"type": "ui-group",
						"name": "group_list",
						"uid": 11005,
						"z": 14,
						"w": 480,
						"h": 800,
						"pivotX": 0.5,
						"pivotY": 0.5,
						"rotation": 0,
						"opacity": 1,
						"hMargin": 0,
						"vMargin": 0,
						"scaleX": 1,
						"scaleY": 1,
						"roundRadius": 5,
						"runtimeVisible": false,
						"enable": true,
						"visible": false,
						"text": "",
						"locked": false,
						"x": 0,
						"y": 0,
						"style": {
							"lineWidth": 2,
							"lineColor": "rgba(0,0,0,0)",
							"fillColor": "#2F3234",
							"textColor": "Blue",
							"fontSize": 24
						},
						"xAttr": 0,
						"yAttr": 0,
						"widthAttr": 2,
						"heightAttr": 2,
						"xParam": 1,
						"yParam": 1,
						"widthParam": 1,
						"heightParam": 1,
						"images": {
							"display": 2
						},
						"events": {
							"onClick": null,
							"onInit": null
						},
						"children": [
							{
								"type": "ui-list-view",
								"name": "list-view",
								"uid": 17368,
								"z": 2,
								"w": 480,
								"h": 759,
								"pivotX": 0.5,
								"pivotY": 0.5,
								"rotation": 0,
								"opacity": 1,
								"hMargin": 0,
								"vMargin": 0,
								"scaleX": 1,
								"scaleY": 1,
								"spacer": 0,
								"runtimeVisible": true,
								"enable": true,
								"visible": true,
								"text": "",
								"x": 0,
								"y": 42,
								"style": {
									"lineWidth": 2,
									"lineColor": "Orange",
									"fillColor": "#f0f0f0",
									"textColor": "Blue",
									"fontSize": 16,
									"fontFamily": "serif"
								},
								"itemHeightVariable": true,
								"itemHeight": 78,
								"xAttr": 2,
								"yAttr": 2,
								"widthAttr": 2,
								"heightAttr": 3,
								"xParam": 0,
								"yParam": 0.0525,
								"widthParam": 1,
								"heightParam": 1,
								"images": {
									"display": 2,
									"scrollBarImg": "assets/controls/scrollbar.png"
								},
								"events": {
									"onClick": null,
									"onUpdateData": null,
									"onScrollOutOfRange": null
								},
								"children": [
									{
										"type": "ui-list-item",
										"name": "item_0",
										"uid": 19213,
										"z": 0,
										"w": 480,
										"h": 78,
										"pivotX": 0.5,
										"pivotY": 0.5,
										"rotation": 0,
										"opacity": 1,
										"hMargin": 0,
										"vMargin": 0,
										"scaleX": 1,
										"scaleY": 1,
										"roundRadius": 5,
										"runtimeVisible": true,
										"enable": true,
										"visible": true,
										"text": "",
										"x": 0,
										"y": 0,
										"style": {
											"lineWidth": 2,
											"lineColor": "#C8C8C8",
											"fillColor": "#b8b8b8",
											"textColor": "rgba(0,0,0,0)",
											"fontSize": 16,
											"fontFamily": "serif"
										},
										"xAttr": 0,
										"yAttr": 0,
										"widthAttr": 2,
										"heightAttr": 0,
										"xParam": 1,
										"yParam": 1,
										"widthParam": 1,
										"heightParam": 1,
										"images": {
											"display": 2
										},
										"events": {
											"onClick": null,
											"onLongPress": null,
											"onRemoved": null
										},
										"children": [
											{
												"type": "ui-label",
												"name": "label_name",
												"uid": 18607,
												"z": 0,
												"w": 300,
												"h": 46,
												"pivotX": 0.5,
												"pivotY": 0.5,
												"rotation": 0,
												"opacity": 1,
												"hMargin": 5,
												"vMargin": 5,
												"scaleX": 1,
												"scaleY": 1,
												"runtimeVisible": true,
												"enable": true,
												"visible": true,
												"text": "Mary",
												"x": 90,
												"y": 15,
												"style": {
													"lineWidth": 2,
													"lineColor": "Red",
													"fillColor": "rgba(0,0,0,0)",
													"textColor": "#ffffff",
													"fontSize": 15,
													"fontFamily": "serif"
												},
												"hTextAlign": "center",
												"vTextAlign": "middle",
												"xAttr": 3,
												"yAttr": 2,
												"widthAttr": 0,
												"heightAttr": 0,
												"xParam": 1,
												"yParam": 0.19230769230769232,
												"widthParam": 1,
												"heightParam": 1,
												"images": {
													"display": 2
												},
												"events": {
													"onClick": null,
													"onChanged": null,
													"onUpdateTransform": null
												},
												"children": []
											},
											{
												"type": "ui-image",
												"name": "image_head",
												"uid": 14168,
												"z": 1,
												"w": 50,
												"h": 50,
												"pivotX": 0.5,
												"pivotY": 0.5,
												"rotation": 0,
												"opacity": 1,
												"hMargin": 0,
												"vMargin": 0,
												"scaleX": 1,
												"scaleY": 1,
												"runtimeVisible": true,
												"enable": true,
												"visible": true,
												"text": "",
												"locked": false,
												"x": 32,
												"y": 14,
												"style": {
													"lineWidth": 2,
													"lineColor": "#7d471b",
													"fillColor": "White",
													"textColor": "Blue",
													"fontSize": 16,
													"fontFamily": "sans"
												},
												"keepSizeWithImage": false,
												"xAttr": 0,
												"yAttr": 3,
												"widthAttr": 0,
												"heightAttr": 0,
												"xParam": 1,
												"yParam": 1,
												"widthParam": 1,
												"heightParam": 1,
												"imageScaleX": "1.000",
												"imageScaleY": "1.000",
												"images": {
													"display": 3,
													"default_bg": "assets/Chat/res/headicon/14.png",
													"option_image_0": "assets/Chat/res/headicon/1.png",
													"option_image_1": "assets/Chat/res/headicon/2.png",
													"option_image_2": "assets/Chat/res/headicon/3.png",
													"option_image_3": "assets/Chat/res/headicon/4.png",
													"option_image_4": "assets/Chat/res/headicon/5.png",
													"option_image_5": "assets/Chat/res/headicon/6.png",
													"option_image_6": "assets/Chat/res/headicon/7.png",
													"option_image_7": "assets/Chat/res/headicon/8.png",
													"option_image_8": "assets/Chat/res/headicon/9.png",
													"option_image_9": "assets/Chat/res/headicon/10.png",
													"option_image_10": "assets/Chat/res/headicon/11.png",
													"option_image_11": "assets/Chat/res/headicon/12.png",
													"option_image_12": "assets/Chat/res/headicon/13.png",
													"option_image_13": "assets/Chat/res/headicon/14.png"
												},
												"events": {
													"onClick": null,
													"onDoubleClick": null,
													"onUpdateTransform": null
												},
												"children": []
											}
										]
									}
								]
							},
							{
								"type": "ui-color-button",
								"name": "btn_top",
								"uid": 11813,
								"z": 3,
								"w": 480,
								"h": 41,
								"pivotX": 0.5,
								"pivotY": 0.5,
								"rotation": 0,
								"opacity": 1,
								"hMargin": 0,
								"vMargin": 0,
								"scaleX": 1,
								"scaleY": 1,
								"roundRadius": 5,
								"runtimeVisible": true,
								"enable": true,
								"visible": true,
								"text": "Group(12)",
								"locked": false,
								"x": 0,
								"y": 0,
								"style": {
									"lineWidth": 0,
									"lineColor": "#666666",
									"fillColor": "#666666",
									"textColor": "#FFFFFF",
									"fontSize": 16,
									"fontFamily": "serif",
									"activeFillColor": "#666666"
								},
								"xAttr": 3,
								"yAttr": 4,
								"widthAttr": 2,
								"heightAttr": 0,
								"xParam": 1,
								"yParam": 1,
								"widthParam": 1,
								"heightParam": 1,
								"images": {
									"display": 2
								},
								"events": {
									"onClick": null,
									"onUpdateTransform": null
								},
								"children": [
									{
										"type": "ui-label",
										"name": "label_ok",
										"uid": 18607,
										"z": 0,
										"w": 45,
										"h": 41,
										"pivotX": 0.5,
										"pivotY": 0.5,
										"rotation": 0,
										"opacity": 1,
										"hMargin": 5,
										"vMargin": 5,
										"scaleX": 1,
										"scaleY": 1,
										"runtimeVisible": true,
										"enable": true,
										"visible": true,
										"text": "OK",
										"x": 429,
										"y": 0,
										"style": {
											"lineWidth": 2,
											"lineColor": "Red",
											"fillColor": "rgba(0,0,0,0)",
											"textColor": "#FAF7F7",
											"fontSize": 14,
											"fontFamily": "serif"
										},
										"hTextAlign": "center",
										"vTextAlign": "middle",
										"xAttr": 1,
										"yAttr": 0,
										"widthAttr": 0,
										"heightAttr": 0,
										"xParam": 6,
										"yParam": 1,
										"widthParam": 1,
										"heightParam": 1,
										"images": {
											"display": 2
										},
										"events": {
											"onClick": "var me = this;\nvar win = this.getWindow();\nvar group_list = win.find(\"group_list\");\ngroup_list.animate({\n   yEnd:         win.height,\n   duration:     300,\n   interpolator: \"a\"\n});",
											"onChanged": null,
											"onUpdateTransform": null
										},
										"children": []
									}
								]
							}
						]
					},
					{
						"type": "ui-group",
						"name": "group_down",
						"uid": 13953,
						"z": 15,
						"w": 480,
						"h": 41,
						"pivotX": 0.5,
						"pivotY": 0.5,
						"rotation": 0,
						"opacity": 1,
						"hMargin": 0,
						"vMargin": 0,
						"scaleX": 1,
						"scaleY": 1,
						"roundRadius": 5,
						"runtimeVisible": true,
						"enable": true,
						"visible": true,
						"text": "",
						"x": 0,
						"y": 755,
						"style": {
							"lineWidth": 2,
							"lineColor": "rgba(0,0,0,0)",
							"fillColor": "rgba(0,0,0,0)",
							"textColor": "Blue",
							"fontSize": 24
						},
						"xAttr": 3,
						"yAttr": 1,
						"widthAttr": 2,
						"heightAttr": 0,
						"xParam": 1,
						"yParam": 4,
						"widthParam": 1,
						"heightParam": 1,
						"images": {
							"display": 2
						},
						"events": {
							"onClick": null,
							"onInit": null
						},
						"children": [
							{
								"type": "ui-mledit",
								"name": "edit_content",
								"uid": 15593,
								"z": 0,
								"w": 410,
								"h": 41,
								"pivotX": 0.5,
								"pivotY": 0.5,
								"rotation": 0,
								"opacity": 1,
								"hMargin": 8,
								"vMargin": 8,
								"scaleX": 1,
								"scaleY": 1,
								"runtimeVisible": true,
								"enable": true,
								"visible": true,
								"text": "",
								"x": 8,
								"y": 1,
								"style": {
									"lineWidth": 2,
									"lineColor": "Red",
									"fillColor": "White",
									"textColor": "#666666",
									"fontSize": 13,
									"fontFamily": "serif"
								},
								"xAttr": 0,
								"yAttr": 2,
								"widthAttr": 0,
								"heightAttr": 0,
								"xParam": 1,
								"yParam": 0.024390243902439025,
								"widthParam": 1,
								"heightParam": 1,
								"images": {
									"display": 2,
									"default_bg": "assets/controls/textarea_normal_bg.png",
									"focused_bg": "assets/controls/textarea_focus_bg.png"
								},
								"events": {
									"onClick": null,
									"onChanged": null,
									"onFocusIn": null,
									"onFocusOut": null
								},
								"children": []
							},
							{
								"type": "ui-button",
								"name": "btn_send",
								"uid": 11205,
								"z": 1,
								"w": 50,
								"h": 41,
								"pivotX": 0.5,
								"pivotY": 0.5,
								"rotation": 0,
								"opacity": 1,
								"hMargin": 5,
								"vMargin": 5,
								"scaleX": 1,
								"scaleY": 1,
								"runtimeVisible": true,
								"enable": true,
								"visible": true,
								"text": "Send",
								"x": 425,
								"y": 0,
								"style": {
									"lineWidth": 2,
									"lineColor": "Red",
									"fillColor": "White",
									"textColor": "#ffffff",
									"fontSize": 18,
									"fontFamily": "serif"
								},
								"xAttr": 1,
								"yAttr": 3,
								"widthAttr": 0,
								"heightAttr": 0,
								"xParam": 5,
								"yParam": 1,
								"widthParam": 1,
								"heightParam": 1,
								"images": {
									"display": 3,
									"active_bg": "assets/controls/button_active.png",
									"normal_bg": "assets/controls/button_normal.png",
									"disable_bg": "assets/controls/button_active.png"
								},
								"events": {
									"onClick": "var content = this.getWindow().find(\"group_down/edit_content\");\n\nif(content.getValue() != \"\")\n{\n    window.send_message(content.getValue());\n    content.setValue(\"\");\n}\nelse\n{\n    alert(\"Unable to send blank message\");\n}\n",
									"onUpdateTransform": null
								},
								"children": []
							}
						]
					},
					{
						"type": "ui-group",
						"name": "group_plus",
						"uid": 17605,
						"z": 16,
						"w": 172,
						"h": 100,
						"pivotX": 0.5,
						"pivotY": 0.5,
						"rotation": 0,
						"opacity": 1,
						"hMargin": 0,
						"vMargin": 0,
						"scaleX": 1,
						"scaleY": 1,
						"roundRadius": 5,
						"runtimeVisible": false,
						"enable": true,
						"visible": false,
						"text": "",
						"x": 305,
						"y": 46,
						"style": {
							"lineWidth": 0,
							"lineColor": "#000000",
							"fillColor": "#2f3234",
							"textColor": "Blue",
							"fontSize": 24
						},
						"xAttr": 1,
						"yAttr": 0,
						"widthAttr": 0,
						"heightAttr": 0,
						"xParam": 3,
						"yParam": 1,
						"widthParam": 1,
						"heightParam": 1,
						"images": {
							"display": 2
						},
						"events": {
							"onClick": null,
							"onInit": null
						},
						"children": [
							{
								"type": "ui-list-view",
								"name": "list-view",
								"uid": 17368,
								"z": 0,
								"w": 172,
								"h": 150,
								"pivotX": 0.5,
								"pivotY": 0.5,
								"rotation": 0,
								"opacity": 1,
								"hMargin": 0,
								"vMargin": 0,
								"scaleX": 1,
								"scaleY": 1,
								"spacer": 0,
								"runtimeVisible": true,
								"enable": true,
								"visible": true,
								"text": "",
								"x": 0,
								"y": 0,
								"style": {
									"lineWidth": 2,
									"lineColor": "Orange",
									"fillColor": "#f0f0f0",
									"textColor": "Blue",
									"fontSize": 16,
									"fontFamily": "serif"
								},
								"itemHeightVariable": false,
								"itemHeight": 50,
								"xAttr": 3,
								"yAttr": 4,
								"widthAttr": 2,
								"heightAttr": 3,
								"xParam": 1,
								"yParam": 1,
								"widthParam": 1,
								"heightParam": 1,
								"images": {
									"display": 2,
									"scrollBarImg": "assets/controls/scrollbar.png"
								},
								"events": {
									"onClick": null,
									"onUpdateData": null,
									"onScrollOutOfRange": null
								},
								"children": [
									{
										"type": "ui-list-item",
										"name": "item_0",
										"uid": 19213,
										"z": 0,
										"w": 172,
										"h": 50,
										"pivotX": 0.5,
										"pivotY": 0.5,
										"rotation": 0,
										"opacity": 1,
										"hMargin": 0,
										"vMargin": 0,
										"scaleX": 1,
										"scaleY": 1,
										"roundRadius": 5,
										"runtimeVisible": true,
										"enable": true,
										"visible": true,
										"text": "",
										"x": 0,
										"y": 0,
										"style": {
											"lineWidth": 2,
											"lineColor": "#C8C8C8",
											"fillColor": "#000000",
											"textColor": "rgba(0,0,0,0)",
											"fontSize": 16,
											"fontFamily": "serif"
										},
										"xAttr": 0,
										"yAttr": 0,
										"widthAttr": 2,
										"heightAttr": 0,
										"xParam": 1,
										"yParam": 1,
										"widthParam": 1,
										"heightParam": 1,
										"images": {
											"display": 2
										},
										"events": {
											"onClick": "var me = this;\nvar win = this.getWindow();\nvar group_list = win.find(\"group_list\");\nvar group_plus = win.find(\"group_plus\");\nvar btn_top = group_list.find(\"btn_top\");\nvar list_view  = group_list.find(\"list-view\");\nvar origin_len = list_view.children.length;\nvar len = 0;\n\nfor(var i in window.client_list)\n{\n    var child = null;\n    var color = (window.client_list[i] == window.player_name) ? \"#ff0000\" : \"#ffffff\";\n    \n    if(origin_len > len)\n    {\n        child = list_view.children[len];\n    }\n    else\n    {\n        child = list_view.dupChild(list_view.children[0].name);\n    }\n    \n    child.find(\"image_head\").setValue(window.client_list[i].charCodeAt() % 14);\n    child.find(\"label_name\").setValue(window.client_list[i]);\n    child.find(\"label_name\").setTextColor(color);\n    child.setVisible(true);\n    len ++;\n}\n\nif(len < origin_len)\n{\n    for(i = len; i < list_view.children.length; i++)\n    {\n        list_view.children[i].setVisible(false);\n    }\n}\n\nbtn_top.setValue(\"Group(\" + len + \")\");\ngroup_list.y = win.height;\ngroup_list.setVisible(true);\ngroup_list.animate({\n   yEnd:         0,\n   duration:     400,\n   interpolator: \"ad\"\n});\ngroup_plus.setVisible(false);",
											"onLongPress": null,
											"onRemoved": null
										},
										"children": [
											{
												"type": "ui-label",
												"name": "ui-label",
												"uid": 19216,
												"z": 2,
												"w": 172,
												"h": 39,
												"pivotX": 0.5,
												"pivotY": 0.5,
												"rotation": 0,
												"opacity": 1,
												"hMargin": 5,
												"vMargin": 5,
												"scaleX": 1,
												"scaleY": 1,
												"runtimeVisible": true,
												"enable": true,
												"visible": true,
												"text": "Group Members",
												"x": 0,
												"y": 5,
												"style": {
													"lineWidth": 2,
													"lineColor": "Green",
													"fillColor": "white",
													"textColor": "#ffffff",
													"fontSize": 17,
													"fontFamily": "serif"
												},
												"hTextAlign": "center",
												"vTextAlign": "middle",
												"xAttr": 0,
												"yAttr": 3,
												"widthAttr": 2,
												"heightAttr": 0,
												"xParam": 1,
												"yParam": 1,
												"widthParam": 1,
												"heightParam": 1,
												"images": {
													"display": 2
												},
												"events": {
													"onClick": null,
													"onChanged": null,
													"onUpdateTransform": null
												},
												"children": []
											}
										]
									},
									{
										"type": "ui-list-item",
										"name": "item_1",
										"uid": 19213,
										"z": 1,
										"w": 172,
										"h": 50,
										"pivotX": 0.5,
										"pivotY": 0.5,
										"rotation": 0,
										"opacity": 1,
										"hMargin": 0,
										"vMargin": 0,
										"scaleX": 1,
										"scaleY": 1,
										"roundRadius": 5,
										"runtimeVisible": true,
										"enable": true,
										"visible": true,
										"text": "",
										"x": 0,
										"y": 50,
										"style": {
											"lineWidth": 2,
											"lineColor": "#C8C8C8",
											"fillColor": "#000000",
											"textColor": "rgba(0,0,0,0)",
											"fontSize": 16,
											"fontFamily": "serif",
											"overFillColor": "#b8b8b8",
											"focusedFillColor": "#000000"
										},
										"xAttr": 0,
										"yAttr": 0,
										"widthAttr": 2,
										"heightAttr": 0,
										"xParam": 1,
										"yParam": 1,
										"widthParam": 1,
										"heightParam": 1,
										"images": {
											"display": 2
										},
										"events": {
											"onClick": "var me = this;\nvar win = this.getWindow();\n//显示对象\nwin.find(\"group_plus\").setVisible(false);\nwin.find(\"group_qr\").setVisible(true);",
											"onLongPress": null,
											"onRemoved": null
										},
										"children": [
											{
												"type": "ui-label",
												"name": "ui-label",
												"uid": 19216,
												"z": 1,
												"w": 172,
												"h": 39,
												"pivotX": 0.5,
												"pivotY": 0.5,
												"rotation": 0,
												"opacity": 1,
												"hMargin": 5,
												"vMargin": 5,
												"scaleX": 1,
												"scaleY": 1,
												"runtimeVisible": true,
												"enable": true,
												"visible": true,
												"text": "QR Code",
												"x": 0,
												"y": 5,
												"style": {
													"lineWidth": 2,
													"lineColor": "Green",
													"fillColor": "white",
													"textColor": "#ffffff",
													"fontSize": 17,
													"fontFamily": "serif"
												},
												"hTextAlign": "center",
												"vTextAlign": "middle",
												"xAttr": 0,
												"yAttr": 3,
												"widthAttr": 2,
												"heightAttr": 0,
												"xParam": 1,
												"yParam": 1,
												"widthParam": 1,
												"heightParam": 1,
												"images": {
													"display": 2
												},
												"events": {
													"onClick": null,
													"onChanged": null,
													"onUpdateTransform": null
												},
												"children": []
											}
										]
									},
									{
										"type": "ui-list-item",
										"name": "item_2",
										"uid": 19213,
										"z": 2,
										"w": 172,
										"h": 50,
										"pivotX": 0.5,
										"pivotY": 0.5,
										"rotation": 0,
										"opacity": 1,
										"hMargin": 0,
										"vMargin": 0,
										"scaleX": 1,
										"scaleY": 1,
										"roundRadius": 5,
										"runtimeVisible": true,
										"enable": true,
										"visible": true,
										"text": "",
										"locked": false,
										"x": 0,
										"y": 100,
										"style": {
											"lineWidth": 2,
											"lineColor": "#C8C8C8",
											"fillColor": "#000000",
											"textColor": "rgba(0,0,0,0)",
											"fontSize": 16,
											"fontFamily": "serif",
											"overFillColor": "#b8b8b8",
											"focusedFillColor": "#000000"
										},
										"xAttr": 0,
										"yAttr": 0,
										"widthAttr": 2,
										"heightAttr": 0,
										"xParam": 1,
										"yParam": 1,
										"widthParam": 1,
										"heightParam": 1,
										"images": {
											"display": 2
										},
										"events": {
											"onClick": "var me = this;\nvar win = this.getWindow();\n//显示对象\nwin.find(\"group_plus\").setVisible(false);\nalert(\"Chat By Pury. \\r\\r Version: 0.0.1\");",
											"onLongPress": null,
											"onRemoved": null
										},
										"children": [
											{
												"type": "ui-label",
												"name": "ui-label",
												"uid": 19216,
												"z": 1,
												"w": 172,
												"h": 39,
												"pivotX": 0.5,
												"pivotY": 0.5,
												"rotation": 0,
												"opacity": 1,
												"hMargin": 5,
												"vMargin": 5,
												"scaleX": 1,
												"scaleY": 1,
												"runtimeVisible": true,
												"enable": true,
												"visible": true,
												"text": "About",
												"x": 0,
												"y": 5,
												"style": {
													"lineWidth": 2,
													"lineColor": "Green",
													"fillColor": "white",
													"textColor": "#ffffff",
													"fontSize": 17,
													"fontFamily": "serif"
												},
												"hTextAlign": "center",
												"vTextAlign": "middle",
												"xAttr": 0,
												"yAttr": 3,
												"widthAttr": 2,
												"heightAttr": 0,
												"xParam": 1,
												"yParam": 1,
												"widthParam": 1,
												"heightParam": 1,
												"images": {
													"display": 2
												},
												"events": {
													"onClick": null,
													"onChanged": null,
													"onUpdateTransform": null
												},
												"children": []
											}
										]
									}
								]
							}
						]
					},
					{
						"type": "ui-group",
						"name": "group_qr",
						"uid": 17605,
						"z": 18,
						"w": 480,
						"h": 800,
						"pivotX": 0.5,
						"pivotY": 0.5,
						"rotation": 0,
						"opacity": 1,
						"hMargin": 0,
						"vMargin": 0,
						"scaleX": 1,
						"scaleY": 1,
						"roundRadius": 0,
						"runtimeVisible": false,
						"enable": true,
						"visible": false,
						"text": "",
						"x": 0,
						"y": 0,
						"style": {
							"lineWidth": 0,
							"lineColor": "rgba(0,0,0,0)",
							"fillColor": "#666666",
							"textColor": "Blue",
							"fontSize": 24
						},
						"xAttr": 2,
						"yAttr": 2,
						"widthAttr": 2,
						"heightAttr": 2,
						"xParam": 0,
						"yParam": 0,
						"widthParam": 1,
						"heightParam": 1,
						"images": {
							"display": 2
						},
						"events": {
							"onClick": "var me = this;\nvar win = this.getWindow();\n//显示对象\nthis.setVisible(false);",
							"onInit": null
						},
						"children": [
							{
								"type": "ui-image",
								"name": "image",
								"uid": 14168,
								"z": 0,
								"w": 182,
								"h": 183,
								"pivotX": 0.5,
								"pivotY": 0.5,
								"rotation": 0,
								"opacity": 1,
								"hMargin": 0,
								"vMargin": 0,
								"scaleX": 1,
								"scaleY": 1,
								"runtimeVisible": true,
								"enable": true,
								"visible": true,
								"text": "",
								"locked": false,
								"x": 149,
								"y": 308,
								"style": {
									"lineWidth": 2,
									"lineColor": "#7d471b",
									"fillColor": "White",
									"textColor": "Blue",
									"fontSize": 16,
									"fontFamily": "sans"
								},
								"keepSizeWithImage": false,
								"xAttr": 3,
								"yAttr": 3,
								"widthAttr": 0,
								"heightAttr": 0,
								"xParam": 1,
								"yParam": 1,
								"widthParam": 1,
								"heightParam": 1,
								"imageScaleX": "1.000",
								"imageScaleY": "1.000",
								"images": {
									"display": 3,
									"default_bg": "assets/Chat/res/qr.png"
								},
								"events": {
									"onClick": null,
									"onDoubleClick": null,
									"onUpdateTransform": null
								},
								"children": []
							}
						]
					}
				]
			},
			{
				"type": "ui-scene",
				"name": "scene",
				"uid": 16617,
				"z": 5,
				"w": 480,
				"h": 800,
				"pivotX": 0.5,
				"pivotY": 0.5,
				"rotation": 0,
				"opacity": 1,
				"hMargin": 0,
				"vMargin": 0,
				"scaleX": 1,
				"scaleY": 1,
				"runtimeVisible": true,
				"enable": true,
				"visible": true,
				"text": "",
				"x": 0,
				"y": 0,
				"style": {
					"lineWidth": 2,
					"lineColor": "#C8C8C8",
					"fillColor": "#2F3234",
					"textColor": "Blue",
					"fontSize": 15,
					"fontFamily": "sans"
				},
				"enablePhysics": true,
				"gravityY": 10,
				"pixelsPerMeter": 100,
				"virtualWidth": 0,
				"virtualHeight": 0,
				"xOffset": 0,
				"yOffset": 0,
				"animHint": "none",
				"sceneId": "game_scene_2",
				"xAttr": 0,
				"yAttr": 0,
				"widthAttr": 2,
				"heightAttr": 2,
				"xParam": 1,
				"yParam": 1,
				"widthParam": 1,
				"heightParam": 1,
				"images": {
					"display": 3
				},
				"events": {
					"onClick": null,
					"onSystemInit": null,
					"onLoad": null,
					"onOpen": null,
					"onBeforeOpen": null,
					"onClose": null,
					"onSwitchToBack": null,
					"onSwitchToFront": null,
					"onGesture": null,
					"onKeyDown": null,
					"onKeyUp": null,
					"onPointerDown": null,
					"onPointerMove": null,
					"onPointerUp": null,
					"onDoubleClick": null,
					"onMultiTouch": null,
					"onSwipeLeft": null,
					"onSwipeRight": null,
					"onSwipeUp": null,
					"onSwipeDown": null,
					"onRelayout": null,
					"onUnload": null
				},
				"settings": {},
				"children": [
					{
						"type": "ui-group",
						"name": "group_list",
						"uid": 11005,
						"z": 0,
						"w": 480,
						"h": 800,
						"pivotX": 0.5,
						"pivotY": 0.5,
						"rotation": 0,
						"opacity": 1,
						"hMargin": 0,
						"vMargin": 0,
						"scaleX": 1,
						"scaleY": 1,
						"roundRadius": 5,
						"runtimeVisible": true,
						"enable": true,
						"visible": true,
						"text": "",
						"locked": false,
						"x": 0,
						"y": 0,
						"style": {
							"lineWidth": 2,
							"lineColor": "rgba(0,0,0,0)",
							"fillColor": "rgba(0,0,0,0)",
							"textColor": "Blue",
							"fontSize": 24
						},
						"xAttr": 0,
						"yAttr": 0,
						"widthAttr": 2,
						"heightAttr": 2,
						"xParam": 1,
						"yParam": 1,
						"widthParam": 1,
						"heightParam": 1,
						"images": {
							"display": 2
						},
						"events": {
							"onClick": null,
							"onInit": null
						},
						"children": [
							{
								"type": "ui-list-view",
								"name": "list-view",
								"uid": 17368,
								"z": 2,
								"w": 480,
								"h": 759,
								"pivotX": 0.5,
								"pivotY": 0.5,
								"rotation": 0,
								"opacity": 1,
								"hMargin": 0,
								"vMargin": 0,
								"scaleX": 1,
								"scaleY": 1,
								"spacer": 0,
								"runtimeVisible": true,
								"enable": true,
								"visible": true,
								"text": "",
								"x": 0,
								"y": 42,
								"style": {
									"lineWidth": 2,
									"lineColor": "Orange",
									"fillColor": "#f0f0f0",
									"textColor": "Blue",
									"fontSize": 16,
									"fontFamily": "serif"
								},
								"itemHeightVariable": false,
								"itemHeight": 78,
								"xAttr": 2,
								"yAttr": 2,
								"widthAttr": 2,
								"heightAttr": 3,
								"xParam": 0,
								"yParam": 0.0525,
								"widthParam": 1,
								"heightParam": 1,
								"images": {
									"display": 2,
									"scrollBarImg": "assets/controls/scrollbar.png"
								},
								"events": {
									"onClick": null,
									"onUpdateData": null,
									"onScrollOutOfRange": null
								},
								"children": [
									{
										"type": "ui-list-item",
										"name": "item_0",
										"uid": 19213,
										"z": 0,
										"w": 480,
										"h": 78,
										"pivotX": 0.5,
										"pivotY": 0.5,
										"rotation": 0,
										"opacity": 1,
										"hMargin": 0,
										"vMargin": 0,
										"scaleX": 1,
										"scaleY": 1,
										"roundRadius": 5,
										"runtimeVisible": true,
										"enable": true,
										"visible": true,
										"text": "",
										"x": 0,
										"y": 0,
										"style": {
											"lineWidth": 2,
											"lineColor": "#C8C8C8",
											"fillColor": "#b8b8b8",
											"textColor": "rgba(0,0,0,0)",
											"fontSize": 16,
											"fontFamily": "serif"
										},
										"xAttr": 0,
										"yAttr": 0,
										"widthAttr": 2,
										"heightAttr": 0,
										"xParam": 1,
										"yParam": 1,
										"widthParam": 1,
										"heightParam": 1,
										"images": {
											"display": 2
										},
										"events": {
											"onClick": null,
											"onLongPress": null,
											"onRemoved": null
										},
										"children": [
											{
												"type": "ui-label",
												"name": "label_name",
												"uid": 18607,
												"z": 0,
												"w": 300,
												"h": 46,
												"pivotX": 0.5,
												"pivotY": 0.5,
												"rotation": 0,
												"opacity": 1,
												"hMargin": 5,
												"vMargin": 5,
												"scaleX": 1,
												"scaleY": 1,
												"runtimeVisible": true,
												"enable": true,
												"visible": true,
												"text": "Mary",
												"x": 90,
												"y": 15,
												"style": {
													"lineWidth": 2,
													"lineColor": "Red",
													"fillColor": "rgba(0,0,0,0)",
													"textColor": "#ffffff",
													"fontSize": 15,
													"fontFamily": "serif"
												},
												"hTextAlign": "center",
												"vTextAlign": "middle",
												"xAttr": 3,
												"yAttr": 2,
												"widthAttr": 0,
												"heightAttr": 0,
												"xParam": 1,
												"yParam": 0.19230769230769232,
												"widthParam": 1,
												"heightParam": 1,
												"images": {
													"display": 2
												},
												"events": {
													"onClick": null,
													"onChanged": null,
													"onUpdateTransform": null
												},
												"children": []
											},
											{
												"type": "ui-image",
												"name": "image_head",
												"uid": 14168,
												"z": 1,
												"w": 50,
												"h": 50,
												"pivotX": 0.5,
												"pivotY": 0.5,
												"rotation": 0,
												"opacity": 1,
												"hMargin": 0,
												"vMargin": 0,
												"scaleX": 1,
												"scaleY": 1,
												"runtimeVisible": true,
												"enable": true,
												"visible": true,
												"text": "",
												"locked": false,
												"x": 28,
												"y": 13,
												"style": {
													"lineWidth": 2,
													"lineColor": "#7d471b",
													"fillColor": "White",
													"textColor": "Blue",
													"fontSize": 16,
													"fontFamily": "sans"
												},
												"keepSizeWithImage": false,
												"xAttr": 0,
												"yAttr": 2,
												"widthAttr": 0,
												"heightAttr": 0,
												"xParam": 1,
												"yParam": 0.16666666666666666,
												"widthParam": 1,
												"heightParam": 1,
												"images": {
													"display": 3,
													"default_bg": "assets/Chat/res/headicon/3.png",
													"option_image_0": "assets/Chat/res/headicon/1.png",
													"option_image_1": "assets/Chat/res/headicon/2.png",
													"option_image_2": "assets/Chat/res/headicon/3.png",
													"option_image_3": "assets/Chat/res/headicon/4.png",
													"option_image_4": "assets/Chat/res/headicon/5.png",
													"option_image_5": "assets/Chat/res/headicon/6.png"
												},
												"events": {
													"onClick": null,
													"onDoubleClick": null,
													"onUpdateTransform": null
												},
												"children": []
											}
										]
									}
								]
							},
							{
								"type": "ui-color-button",
								"name": "btn_top",
								"uid": 11813,
								"z": 3,
								"w": 480,
								"h": 41,
								"pivotX": 0.5,
								"pivotY": 0.5,
								"rotation": 0,
								"opacity": 1,
								"hMargin": 0,
								"vMargin": 0,
								"scaleX": 1,
								"scaleY": 1,
								"roundRadius": 5,
								"runtimeVisible": true,
								"enable": true,
								"visible": true,
								"text": "Group(12)",
								"locked": false,
								"x": 0,
								"y": 0,
								"style": {
									"lineWidth": 0,
									"lineColor": "#666666",
									"fillColor": "#666666",
									"textColor": "#FFFFFF",
									"fontSize": 16,
									"fontFamily": "serif",
									"activeFillColor": "#666666"
								},
								"xAttr": 3,
								"yAttr": 4,
								"widthAttr": 2,
								"heightAttr": 0,
								"xParam": 1,
								"yParam": 1,
								"widthParam": 1,
								"heightParam": 1,
								"images": {
									"display": 2
								},
								"events": {
									"onClick": null,
									"onUpdateTransform": null
								},
								"children": [
									{
										"type": "ui-label",
										"name": "label_ok",
										"uid": 18607,
										"z": 0,
										"w": 45,
										"h": 41,
										"pivotX": 0.5,
										"pivotY": 0.5,
										"rotation": 0,
										"opacity": 1,
										"hMargin": 5,
										"vMargin": 5,
										"scaleX": 1,
										"scaleY": 1,
										"runtimeVisible": true,
										"enable": true,
										"visible": true,
										"text": "OK",
										"x": 429,
										"y": 1,
										"style": {
											"lineWidth": 2,
											"lineColor": "Red",
											"fillColor": "rgba(0,0,0,0)",
											"textColor": "#FAF7F7",
											"fontSize": 14,
											"fontFamily": "serif"
										},
										"hTextAlign": "center",
										"vTextAlign": "middle",
										"xAttr": 1,
										"yAttr": 0,
										"widthAttr": 0,
										"heightAttr": 0,
										"xParam": 6,
										"yParam": 1,
										"widthParam": 1,
										"heightParam": 1,
										"images": {
											"display": 2
										},
										"events": {
											"onClick": "var target = this.getWindow().find(\"group_list/list-view\");\ntarget.dupChild(\"item_0\");",
											"onChanged": null,
											"onUpdateTransform": null
										},
										"children": []
									}
								]
							}
						]
					}
				]
			},
			{
				"type": "ui-scene",
				"name": "scene2",
				"uid": 16617,
				"z": 6,
				"w": 480,
				"h": 800,
				"pivotX": 0.5,
				"pivotY": 0.5,
				"rotation": 0,
				"opacity": 1,
				"hMargin": 0,
				"vMargin": 0,
				"scaleX": 1,
				"scaleY": 1,
				"runtimeVisible": true,
				"enable": true,
				"visible": true,
				"text": "",
				"x": 0,
				"y": 0,
				"style": {
					"lineWidth": 2,
					"lineColor": "#C8C8C8",
					"fillColor": "#2F3234",
					"textColor": "Blue",
					"fontSize": 15,
					"fontFamily": "sans"
				},
				"enablePhysics": true,
				"gravityY": 10,
				"pixelsPerMeter": 100,
				"virtualWidth": 0,
				"virtualHeight": 0,
				"xOffset": 0,
				"yOffset": 0,
				"animHint": "none",
				"sceneId": "game_scene_3",
				"xAttr": 0,
				"yAttr": 0,
				"widthAttr": 2,
				"heightAttr": 2,
				"xParam": 1,
				"yParam": 1,
				"widthParam": 1,
				"heightParam": 1,
				"images": {
					"display": 3
				},
				"events": {
					"onClick": "var me = this;\nvar win = this.getWindow();\n//Show Object\nvar list = win.find(\"list-view\");\nvar child = list.dupChild(\"item\");\nwindow.num = window.num || 0;\nchild.find(\"label\").setValue(window.num++);\n",
					"onSystemInit": null,
					"onLoad": null,
					"onOpen": null,
					"onBeforeOpen": null,
					"onClose": null,
					"onSwitchToBack": null,
					"onSwitchToFront": null,
					"onGesture": null,
					"onKeyDown": null,
					"onKeyUp": null,
					"onPointerDown": null,
					"onPointerMove": null,
					"onPointerUp": null,
					"onDoubleClick": null,
					"onMultiTouch": null,
					"onSwipeLeft": null,
					"onSwipeRight": null,
					"onSwipeUp": null,
					"onSwipeDown": null,
					"onRelayout": null,
					"onUnload": null
				},
				"settings": {},
				"children": [
					{
						"type": "ui-list-view",
						"name": "list-view",
						"uid": 17368,
						"z": 0,
						"w": 480,
						"h": 652,
						"pivotX": 0.5,
						"pivotY": 0.5,
						"rotation": 0,
						"opacity": 1,
						"hMargin": 0,
						"vMargin": 0,
						"scaleX": 1,
						"scaleY": 1,
						"spacer": 0,
						"runtimeVisible": true,
						"enable": true,
						"visible": true,
						"text": "",
						"x": 0,
						"y": 148,
						"style": {
							"lineWidth": 2,
							"lineColor": "Orange",
							"fillColor": "#f0f0f0",
							"textColor": "Blue",
							"fontSize": 16,
							"fontFamily": "serif"
						},
						"itemHeightVariable": false,
						"itemHeight": 120,
						"xAttr": 2,
						"yAttr": 2,
						"widthAttr": 2,
						"heightAttr": 3,
						"xParam": 0,
						"yParam": 0.185,
						"widthParam": 1,
						"heightParam": 1,
						"images": {
							"display": 2,
							"scrollBarImg": "assets/controls/scrollbar.png"
						},
						"events": {
							"onClick": null,
							"onUpdateData": null,
							"onScrollOutOfRange": null
						},
						"children": [
							{
								"type": "ui-list-item",
								"name": "item",
								"uid": 19213,
								"z": 0,
								"w": 480,
								"h": 120,
								"pivotX": 0.5,
								"pivotY": 0.5,
								"rotation": 0,
								"opacity": 1,
								"hMargin": 0,
								"vMargin": 0,
								"scaleX": 1,
								"scaleY": 1,
								"roundRadius": 5,
								"runtimeVisible": true,
								"enable": true,
								"visible": true,
								"text": "",
								"x": 0,
								"y": 0,
								"style": {
									"lineWidth": 1,
									"lineColor": "",
									"fillColor": "",
									"textColor": "",
									"fontSize": 16,
									"fontFamily": "serif",
									"focusedFillColor": "",
									"overFillColor": ""
								},
								"xAttr": 0,
								"yAttr": 0,
								"widthAttr": 2,
								"heightAttr": 0,
								"xParam": 1,
								"yParam": 1,
								"widthParam": 1,
								"heightParam": 1,
								"images": {
									"display": 2
								},
								"events": {
									"onClick": null,
									"onLongPress": null,
									"onRemoved": null
								},
								"children": [
									{
										"type": "ui-label",
										"name": "label",
										"uid": 19216,
										"z": 2,
										"w": 375,
										"h": 77,
										"pivotX": 0.5,
										"pivotY": 0.5,
										"rotation": 0,
										"opacity": 1,
										"hMargin": 5,
										"vMargin": 5,
										"scaleX": 1,
										"scaleY": 1,
										"runtimeVisible": true,
										"enable": true,
										"visible": true,
										"text": "text",
										"x": 52,
										"y": 21,
										"style": {
											"lineWidth": 2,
											"lineColor": "Green",
											"fillColor": "white",
											"textColor": "#ffffff",
											"fontSize": 36,
											"fontFamily": "serif"
										},
										"hTextAlign": "center",
										"vTextAlign": "middle",
										"xAttr": 3,
										"yAttr": 3,
										"widthAttr": 0,
										"heightAttr": 0,
										"xParam": 1,
										"yParam": 1,
										"widthParam": 1,
										"heightParam": 1,
										"images": {
											"display": 2
										},
										"events": {
											"onClick": null,
											"onChanged": null,
											"onUpdateTransform": null
										},
										"children": []
									},
									{
										"type": "ui-color-bar",
										"name": "color-bar",
										"uid": 11820,
										"z": 3,
										"w": 480,
										"h": 20,
										"pivotX": 0.5,
										"pivotY": 0.5,
										"rotation": 0,
										"opacity": 1,
										"hMargin": 0,
										"vMargin": 0,
										"scaleX": 1,
										"scaleY": 1,
										"runtimeVisible": true,
										"enable": true,
										"visible": true,
										"text": "",
										"x": 0,
										"y": 100,
										"style": {
											"lineWidth": 4,
											"lineColor": "#ffffff",
											"fillColor": "White",
											"textColor": "Blue",
											"fontSize": 24,
											"fontFamily": "serif"
										},
										"barPosition": 1,
										"xAttr": 2,
										"yAttr": 5,
										"widthAttr": 2,
										"heightAttr": 0,
										"xParam": 0,
										"yParam": 1,
										"widthParam": 1,
										"heightParam": 1,
										"images": {
											"display": 2
										},
										"events": {
											"onClick": null
										},
										"children": []
									}
								]
							}
						]
					}
				]
			}
		]
	}
}